# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: E r a C o d e s
email: ani16september@gmail.com
author: AnimeshRy
copyright: Copyright © 2020
description: >- # this means to ignore newlines until "baseurl:"
  EraCodes

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "animeshry.github.io" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/blog/assets/images/favicon.ico" # the favicon for your site

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%b %d, %Y"

# If you want more debug log, you can set true
# debug: false

# If you don't want transparent header, you can set false
# header_transparent: true

# Google analytics
# google_analytics: [Tracking ID]

# If you want to generate website sitemap, you can set true
# sitemap: false

# If you want to change site language, you can set lang option
# lang: "en"  # default lang is en

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: en
    img: "/blog/assets/images/banners/en.png"
    text: English

  - lang: fr
    img: "/blog/assets/images/banners/fr.png"
    text: French

  - lang: zh-CN
    img: "/blog/assets/images/banners/chn.png"
    text: Chinese(Simple)

  - lang: ja
    img: "/blog/assets/images/banners/jpn.png"
    text: Japan


# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
#
# Custom color as below:
# theme_color: "#882250"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for always on/off.
# night_mode: "auto"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - categories.html
  - archives.html
  - tags.html
  - about.html

# Page default value
defaults:
  home:
    heading: ""
    subheading: ""
    banner: "Your image url"

# Pagination setting
paginate: 5

# Disqus comments
# disqus:
#   shortname: "era5tone"

# Gitment comments
# gitment:
#   username: "AnimeshRy"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
